services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass123
      MARIADB_DATABASE: demodb
      MARIADB_USER: demouser
      MARIADB_PASSWORD: demopass123
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - db-net


  adminer:
    image: adminer:latest
    container_name: mariadb-adminer
    restart: always
    ports:
      - "8085:8080"
    networks:
      - db-net


networks:
  db-net:
    driver: bridge

volumes:
  mariadb_data:    
