version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fullstack-backend
    ports:
      - "5000:5000"
    networks:
      - fullstack-net


  frontend:
    image: httpd:latest
    container_name: fullstack-frontend
    ports:
      - "8002:80"
    networks:
      - fullstack-net
    depends_on:
      - backend


  database:
    image: mysql:8.0
    container_name: fullstack-db
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: appdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fullstack-net

networks:
  fullstack-net:
    driver: bridge

volumes:
  db_data:
